/*
* generated by Xtext
*/
package de.saxsys.roo.xtext.example.somedsl.ui.contentassist;

import de.saxsys.roo.xtext.example.somedsl.ui.contentassist.AbstractSomeDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SomeDslProposalProvider extends AbstractSomeDslProposalProvider {

}
