/*
 * generated by Xtext
 */
package de.saxsys.roo.xtext.example.somedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SomeDslUiModule extends de.saxsys.roo.xtext.example.somedsl.ui.AbstractSomeDslUiModule {
	public SomeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
