
/*
 * generated by Xtext
 */
 
package de.saxsys.roo.xtext.example.somedsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class SomeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return de.saxsys.roo.xtext.example.somedsl.ui.internal.SomeDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return de.saxsys.roo.xtext.example.somedsl.ui.internal.SomeDslActivator.getInstance().getInjector("de.saxsys.roo.xtext.example.somedsl.SomeDsl");
	}
	
}
