/*
 * generated by Xtext
 */
package de.saxsys.roo.xtext.example.somedsl;

import org.eclipse.xtext.resource.XtextResourceSet;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SomeDslRuntimeModule extends de.saxsys.roo.xtext.example.somedsl.AbstractSomeDslRuntimeModule {
	public Class<? extends XtextResourceSet> bindXtextResourceSet() {
		return PatchedXtextResourceSet.class;
	}
}
