
/*
 * generated by Xtext
 */
package de.saxsys.roo.xtext.example.somedsl.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class SomeDslActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static SomeDslActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("de.saxsys.roo.xtext.example.somedsl.SomeDsl", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("de.saxsys.roo.xtext.example.somedsl.SomeDsl")).with(getUiModule("de.saxsys.roo.xtext.example.somedsl.SomeDsl"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static SomeDslActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("de.saxsys.roo.xtext.example.somedsl.SomeDsl".equals(grammar)) {
		  return new de.saxsys.roo.xtext.example.somedsl.SomeDslRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("de.saxsys.roo.xtext.example.somedsl.SomeDsl".equals(grammar)) {
		  return new de.saxsys.roo.xtext.example.somedsl.ui.SomeDslUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
