/*
* generated by Xtext
*/
package de.saxsys.roo.xtext.example.somedsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SomeDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
